/**
 * Database types - Generated by Supabase
 * This is a stub file for build compatibility
 * In production, this should be generated from your Supabase schema
 */

export interface Database {
  public: {
    Tables: {
      network_connections: {
        Insert: Record<string, any>;
        Row: Record<string, any>;
        Update: Record<string, any>;
      };
      member_follows: {
        Insert: Record<string, any>;
        Row: Record<string, any>;
        Update: Record<string, any>;
      };
      products: {
        Insert: Record<string, any>;
        Row: Record<string, any>;
        Update: Record<string, any>;
      };
      prices: {
        Insert: Record<string, any>;
        Row: Record<string, any>;
        Update: Record<string, any>;
      };
      [key: string]: {
        Insert: Record<string, any>;
        Row: Record<string, any>;
        Update: Record<string, any>;
      };
    };
  };
}

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];

